checkpoint-path: .\experiments\segformerB0_tubes\000_segformerB0_tubes\checkpoints\225.pth

torch-device: cpu # 'cpu' or 'gpu' is supported

gpu: 0

debug: False

timing: False

limit-longest-size: 960