name: interactive-segmentation
channels:
  - defaults
  - conda-forge
  - esri
  - fastai
  - pytorch
dependencies:
  - albumentations
  - cudatoolkit
  - easydict
  - ipython
  - mmcv-full
  - nvidia-ml-py3
  - onnx
  - onnxruntime
  - pillow
  - pip
  - pytorch
  - torchvision
  - pyyaml
  - tensorboard
  - termcolor
  - timm
  - pyyaml
  - pip:
    - thop
    - apache-tvm
    - yapf
