name: iseg
channels:
  - bioconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - albumentations
  - cython
  - easydict
  - matplotlib
  - pip
  - python=3.10
  - pytorch
  - scipy
  - scikit-image
  - tensorboard
  - termcolor
  - timm
  - torchvision
  - pip:
    - mmcv
    - setuptools==59.5.0
    - thop
