name: interactive-segmentation
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - albumentations
  - cudatoolkit
  - easydict
  - pillow
  - pip
  - pytorch
  - torchvision
  - pyyaml
  - tensorboard
  - termcolor
  - timm
  - pip:
    - mmcv
    - thop
